### ISSUE TITLE
Code coverage

### ISSUE THREAD

**Issue by foltik** [Foltik/vyos-client-go#11]
Integration testing was implemented with https://github.com/Foltik/vyos-client-go/commit/9b9a46c4ab7257a0e4fc459f7c1fd7628278a648.

It would be nice to have a code coverage report to go along with this.

**Comment by jtcarnes** [comment]
@foltik would you consider using something like codecov for coverage? Free for FOSS and integrates well with GH. Happy to make MR with it or whatever tool you prefer.

**Comment by foltik** [comment]
Sure! I've gone through the setup [here](https://app.codecov.io/gh/foltik/vyos-client-go) and added a `CODECOV_TOKEN` repo secret.

Looks like we just need to update the makefile to emit coverage and add:
```yaml
- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v3
    env: CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```
